# Generated by Django 6.0.5 on 2026-05-24 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('sap', 'SAP (Fuel & Procurement)'), ('utility', 'Utility / Electricity'), ('travel', 'Corporate Travel')], max_length=20)),
                ('filename', models.CharField(blank=True, max_length=500)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='imports/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('total_rows', models.IntegerField(default=0)),
                ('successful_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('suspicious_rows', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('raw_headers', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('scope1_fuel', 'Scope 1 - Fuel Combustion'), ('scope2_electricity', 'Scope 2 - Electricity'), ('scope3_travel', 'Scope 3 - Business Travel'), ('scope3_procurement', 'Scope 3 - Procurement')], max_length=50)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('activity_date', models.DateField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('co2e_kg', models.FloatField(default=0.0)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('cost_gbp', models.FloatField(blank=True, null=True)),
                ('currency_original', models.CharField(blank=True, max_length=10)),
                ('cost_original', models.FloatField(blank=True, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('normalization_notes', models.TextField(blank=True)),
                ('quality_score', models.FloatField(default=1.0)),
                ('quality_issues', models.JSONField(default=list)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('review_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged for Review')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.dataimport')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['-activity_date'],
                'indexes': [models.Index(fields=['tenant', 'review_status'], name='ingestion_n_tenant__3e9974_idx'), models.Index(fields=['tenant', 'category'], name='ingestion_n_tenant__f770cd_idx'), models.Index(fields=['activity_date'], name='ingestion_n_activit_ef9478_idx')],
            },
        ),
    ]
